academics/urls.py
from django.urls import path
from . import views

app_name = 'academics'

urlpatterns = [
    path('aboutacademics/' , views.aboutacademics , name='aboutacademics'),
    path('highschool/' , views.highschool , name='highschool'),
    path('highersecondaryschool/' , views.highersecondaryschool , name='highersecondaryschool'),
    path('schooltiming/' , views.schooltiming , name='schooltiming'),
    path('schoolanthem/' , views.schoolanthem , name='schoolanthem'),
    path('syllabus/' , views.syllabus , name='syllabus'),
    path('media/' , views.syllabus , name='syllabus'),
    # path('', views.allCategories, name='allCategories'),
	# path('<slug:c_slug>/', views.allCategories, name='achievements_category'),
	# path('<slug:c_slug>/<slug:achievements_slug>/', views.AchieveDetails, name='AchieveDetails'),
    # path('' , views.circular , name='circular'),
    # path('' , views.about , name='about'),
    # path('message/' , views.message , name='message'),

]

ees/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('about/', include('school.urls', namespace='aboutus')),
    path('circular/', include('circular.urls', namespace='circular')),
    path('events/', include('events.urls', namespace='events')),
    path('achievements/', include('achievements.urls', namespace='achievements')),
    path('studentcouncil/', include('studentcouncil.urls', namespace='studentcouncil')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('missionstatement/', include('missionstatement.urls', namespace='missionstatement')),
    path('forcebehind/', include('forcebehind.urls', namespace='forcebehind')),
    path('members/', include('members.urls', namespace='members')),
    path('infrastructure/', include('infrastructure.urls', namespace='infrastructure')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admissions/', include('admissions.urls', namespace='admissions')),
    path('ncc/', include('ncc.urls', namespace='ncc')),
    path('academics/', include('academics.urls', namespace='academics')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "EEHS SCHOOL ADMIN"
admin.site.site_title = "EEHS SCHOOL ADMIN"
admin.site.site_index_title = "Welcome To EEHS School Admin Panel"

academics/models.py
from django.db import models

# Create your models here.
class AboutAcademics(models.Model):
    school_terms = models.TextField(default="")
    school_pdf_calender = models.FileField(upload_to='schoolacademiccalenderpdf/')
    awards_scholarships = models.TextField(default="")
    disciplinary_rules = models.TextField(default="")
    examination_promotion = models.TextField(default="")
    leave_of_absence = models.TextField(default="")
    certificate = models.TextField(default="")
    notes_parents_guardians = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.id)

    class Meta:
        verbose_name = 'AboutAcademics'
        verbose_name_plural = 'AboutAcademics'  

class HighSchool(models.Model):
    curriculum_school = models.TextField(default="")
    coscholastic_activities = models.TextField(default="")
    cocurricular_activities = models.TextField(default="")
    work_experience = models.TextField(default="")
    school_uniform = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.id)

    class Meta:
        verbose_name = 'HighSchool'
        verbose_name_plural = 'HighSchool' 

class HigherSecondarySchool(models.Model):
    curriculum_hs = models.TextField(default="") 
    courses_study = models.TextField(default="")
    school_uniform = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.id)

    class Meta:
        verbose_name = 'HigherSecondarySchool'
        verbose_name_plural = 'HigherSecondarySchool' 

class SchoolTiming(models.Model):
    school_timing = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.id)

    class Meta:
        verbose_name = 'SchoolTiming'
        verbose_name_plural = 'SchoolTiming'     

class SchoolAnthem(models.Model):
    school_anthem = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.id)

    class Meta:
        verbose_name = 'SchoolAnthem'
        verbose_name_plural = 'SchoolAnthem'     

class Syllabus(models.Model):
    syllabus_header = models.TextField(default="")
    syllabus_pdf = models.FileField(upload_to='syllabuspdf/')

    def __str__(self):
	    return '{}'.format(self.syllabus_header)

    class Meta:
        verbose_name = 'Syllabus'
        verbose_name_plural = 'Syllabus'               

academics/views.py
from django.shortcuts import render
from .models import AboutAcademics, HighSchool, HigherSecondarySchool, SchoolAnthem, SchoolTiming, Syllabus
# Create your views here.
def aboutacademics(request):
    aboutacademics = AboutAcademics.objects.last()
    template = 'academics/aboutacademics.html'
    context = {
        'aboutacademics': aboutacademics
    }
    return render(request, template, context)

def highschool(request):
    highschool = HighSchool.objects.last()
    template = 'academics/highschool.html'
    context = {
        'highschool': highschool
    }
    return render(request, template, context)

def highersecondaryschool(request):
    highersecondaryschool = HigherSecondarySchool.objects.last()
    template = 'academics/higher.html'
    context = {
        'highersecondaryschool': highersecondaryschool
    }
    return render(request, template, context)

def schooltiming(request):
    schooltiming = SchoolTiming.objects.last()
    template = 'academics/schooltiming.html'
    context = {
        'schooltiming': schooltiming
    }
    return render(request, template, context)

def schoolanthem(request):
    schoolanthem = SchoolAnthem.objects.last()
    template = 'academics/schoolanthem.html'
    context = {
        'schoolanthem': schoolanthem
    }
    return render(request, template, context)  

def syllabus(request):
    syllabus = Syllabus.objects.all()
    template = 'academics/syllabus.html'
    context = {
        'syllabus': syllabus
    }
    return render(request, template, context)    

def syllabus(request):
    syllabus = Syllabus.objects.all()
   
    template = 'academics/syllabus.html'
    context = {
        'syllabus': syllabus
    }
    return render(request, template, context)     

academics/templates/academics/aboutacademics.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>About Academics</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:aboutacademics' %}">About Academics</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#school">School Terms</a>
        </li>
        <li class="nav-item"></li>
            <a class="nav-link" href="#awards">Awards & Scholarships</a>
        <li class="nav-item">
            <a class="nav-link" href="#discipline">Disciplinary Rules</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#exam">Examination & Promotion</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#leave">Leave of Absence</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#certificate">Certificate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#notes">Notes to Parents/Guardians</a>
        </li>
    </ul>
  </nav>
</div>  

<br>
<div class="container" id="school">
<div class="card " >
    <h2 class="card-header alert-primary text-center">School Terms</h2>
    <div class="card-body">
      <!-- <h5 class="card-title"></h5> -->
      <p class="card-text text-justify">{{aboutacademics.school_terms|safe|escape}}</p>
      <a href="{{aboutacademics.school_pdf_calender.url}}" class="btn btn-primary" target="_blank">Go To School Academic Calender</a>
    </div>
  </div>
</div> 
<br>
<div class="container" id="awards">
  <div class="card " >
    <h2 class="card-header alert-info text-center">Awards & Scholarships</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.awards_scholarships|safe|escape}}</p>
    </div>
  </div>
</div>    

<br>
<div class="container" id="discipline">
  <div class="card " >
    <h2 class="card-header alert-warning text-center">Disciplinary Rules</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.disciplinary_rules|safe|escape}}</p>
    </div>
  </div> 
</div> 

<br>
<div class="container" id="exam">
  <div class="card " >
    <h2 class="card-header alert-success text-center">Examination & Promotion</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.examination_promotion|safe|escape}}</p>
    </div>
  </div> 
</div> 
  <br>
<div class="container" id="leave">
  <div class="card " >
    <h2 class="card-header alert-danger text-center">Leave of Absence</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.leave_of_absence|safe|escape}}</p>
    </div>
  </div> 
</div> 
  <br>
<div class="container" id="certificate">
  <div class="card " >
    <h2 class="card-header text-center">Certificate</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.certificate|safe|escape}}</p>
    </div>
  </div>
</div> 
  <br>
<div class="container" id="notes">
  <div class="card " >
    <h2 class="card-header alert-secondary text-center">Notes to Parents/Guardians</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{aboutacademics.notes_parents_guardians|safe|escape}}</p>
    </div>
  </div>
</div> 

<br>
{% endblock body %}

academics/templates/academics/higher.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Higher Secondary School</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:highersecondaryschool' %}">Higher Secondary School</a>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#curi">Curriculum</a>
            </li>
            <li class="nav-item"></li>
                <a class="nav-link" href="#study">Courses of Study</a>
            <li class="nav-item">
                <a class="nav-link" href="#school">School Uniform</a>
            </li>
        </ul>
      </nav>
    </div> 
<br>
<div class="container" id="curi">
    <div class="card ">
        <h2 class="card-header alert alert-primary text-center">Curriculum</h2>
    <div class="card-body">
        <!-- <h5 class="card-title"></h5> -->
        <p class="card-text text-justify">{{highersecondaryschool.curriculum_hs|safe|escape}}</p>
        <a href="{% url 'academics:syllabus' %}" class="btn btn-primary" target="_blank">Go To School Syllabus</a>
    </div>
    </div>
</div>
<br>
<div class="container" id="study">
  <div class="card ">
    <h2 class="card-header alert alert-info text-center">Courses of Study</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highersecondaryschool.courses_study|safe|escape}}</p>
    </div>
  </div>  
</div>
<br>
<div class="container" id="school">
  <div class="card ">
    <h2 class="card-header alert alert-success text-center">School Uniform</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highersecondaryschool.school_uniform|safe|escape}}</p>
    </div>
  </div>
</div>
<br>
{% endblock body %}

academics/templates/academics/highschool.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>High School</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:highschool' %}">High School</a>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#curi">Curriculum</a>
            </li>
            <li class="nav-item"></li>
                <a class="nav-link" href="#schol">Co-Scholastic Activities</a>
            <li class="nav-item">
                <a class="nav-link" href="#cocuri">Co-Curricular Activities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#work">Work Experience</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#school">School Uniform</a>
            </li>
        </ul>
      </nav>
    </div> 
<br>
<div class="container" id="curi">
<div class="card ">
    <h2 class="card-header alert alert-primary text-center">Curriculum</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highschool.curriculum_school|safe|escape}}</p>
      <a href="{% url 'academics:syllabus' %}" class="btn btn-primary" target="_blank">Go To School Syllabus</a>
    </div>
  </div>
</div> 
<br>
<div class="container" id="schol">
  <div class="card ">
    <h2 class="card-header alert alert-info text-center">Co-Scholastic Activities</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highschool.coscholastic_activities|safe|escape}}</p>
    </div>
  </div>  
</div>  
<br> 
<div class="container" id="cocuri">
  <div class="card ">
    <h2 class="card-header alert alert-info text-center">Co-Curricular Activities</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highschool.cocurricular_activities|safe|escape}}</p>
    </div>
  </div>
</div>  
<br>
<div class="container" id="work">
  <div class="card ">
    <h2 class="card-header alert alert-info text-center">Work Experience</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highschool.work_experience|safe|escape}}</p>
    </div>
  </div>
</div>
<br>
<div class="container" id="school">
  <div class="card ">
    <h2 class="card-header alert alert-success text-center">School Uniform</h2>
    <div class="card-body">
      <p class="card-text text-justify">{{highschool.school_uniform|safe|escape}}</p>
    </div>
  </div>
</div>
<br>
{% endblock body %}

academics/templates/academics/schoolanthem.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>School Anthem</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:schoolanthem' %}">School Anthem</a>
                </div>
            </div>
        </div>
    </div>
</section>

<br>
<div class="container">
    <div class="card ">
        <h2 class="card-header alert alert-info text-center">School Anthem</h2>
        <div class="card-body">
        <p class="card-text text-justify">{{schoolanthem.school_anthem|safe|escape}}</p>
        </div>
    </div> 
</div>
{% endblock body %}

academics/templates/academics/schooltiming.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>School Timing</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:schooltiming' %}">School Timing</a>
                </div>
            </div>
        </div>
    </div>
</section>
<br>
<div class="container">
    <div class="card ">
        <h2 class="card-header alert alert-info text-center">School Timing</h2>
        <div class="card-body">
        <p class="card-text text-justify">{{schooltiming.school_timing|safe|escape}}</p>
        </div>
  </div> 
</div>  
<br>

{% endblock body %}

academics/templates/academics/syllabus.html
{% extends 'base.html' %}
{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Syllabus</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'academics:syllabus' %}">Syllabus</a>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="jumbotron">
    <h1 class="display-4 text-center">Syllabus for all Classes</h1>
    
  </div>

<div class="container">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Sl No.</th>
                <th scope="col">Class</th>
                <th scope="col">Download Link</th>
              </tr>
            </thead>
            {% for x in syllabus %}
            <tbody>
              <tr>
                <th scope="row">{{x.id}}</th>
                <td>{{x.syllabus_header|safe|escape}}</td>
                <td><a href="{{x.syllabus_pdf.url}}" class="btn btn-primary" target="_blank">Syllabus link</a></td>
              </tr>
             
            </tbody>
            {% endfor %}
          </table>
        

</div> 

{% endblock body %}