ees/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('about/', include('school.urls', namespace='aboutus')),
    path('circular/', include('circular.urls', namespace='circular')),
    path('events/', include('events.urls', namespace='events')),
    path('achievements/', include('achievements.urls', namespace='achievements')),
    path('studentcouncil/', include('studentcouncil.urls', namespace='studentcouncil')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('missionstatement/', include('missionstatement.urls', namespace='missionstatement')),
    path('forcebehind/', include('forcebehind.urls', namespace='forcebehind')),
    path('members/', include('members.urls', namespace='members')),
    path('infrastructure/', include('infrastructure.urls', namespace='infrastructure')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admissions/', include('admissions.urls', namespace='admissions')),
    path('ncc/', include('ncc.urls', namespace='ncc')),
    path('academics/', include('academics.urls', namespace='academics')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "EEHS SCHOOL ADMIN"
admin.site.site_title = "EEHS SCHOOL ADMIN"
admin.site.site_index_title = "Welcome To EEHS School Admin Panel"

infrastructure/urls.py
from django.urls import path
from . import views

app_name = 'infrastructure'

urlpatterns = [
    path('' , views.infrastructure , name='infrastructure'),
    # path('trips/' , views.trips , name='trips'),
    # path('upcomingevents/' , views.upcomingevents , name='upcomingevents'),
    # path('message/' , views.message , name='message'),
    # path('principal/' , views.principal , name='principal'),
    # path('vice_principal/' , views.vice_principal , name='vice_principal'),
    # path('headmistress/' , views.headmistress , name='headmistress'),
]

infrastructure/models.py
from django.db import models

# Create your models here.
class Infrastructure(models.Model):
    image = models.ImageField(upload_to='infrastructure/')
    name = models.CharField(max_length=250)
    paragraph = models.TextField(default="")

    def __str__(self):
	    return '{}'.format(self.name)

    class Meta:
        verbose_name = 'Infrastructure'
        verbose_name_plural = 'Infrastructure'  

infrastructure/views.py
from django.shortcuts import render
from .models import Infrastructure

# Create your views here.
def infrastructure(request):    
    infrastructure = Infrastructure.objects.all()
    template = 'infrastructure/infrastructure.html'
    context = {
        'infrastructure': infrastructure
    }
    return render(request, template, context)

infrastructure/templates/infrastructure/infrastructure.html
{% extends 'base.html' %}

{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Infrastructure</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'infrastructure:infrastructure' %}">Infrastructure</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="jumbotron">
    <h1 class="display-4 text-center">School Infrastructure</h1>
</div>

<div class="container">
    <div class="row">
        <br>
        {% for x in infrastructure %}
        <div class="card mb-3" style="max-width: 100%;">
            <div class="row no-gutters">
            <div class="col-md-4">
                <img src="{{x.image.url}}" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                <h3 class="card-title">{{x.name|safe|escape}}</h3>
                <p class="card-text text-justify">{{x.paragraph|safe|escape}}</p>
                
                </div>
            </div>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>
</div>  


{% endblock body %}