circular/urls.py
from django.urls import path
from . import views

app_name = 'circular'

urlpatterns = [
    path('' , views.circular , name='circular'),
    path('<slug:c_slug>/', views.circular, name='circular_category'),
    # path('' , views.about , name='about'),
    # path('message/' , views.message , name='message'),
    # path('principal/' , views.principal , name='principal'),
    # path('vice_principal/' , views.vice_principal , name='vice_principal'),
    # path('headmistress/' , views.headmistress , name='headmistress'),
]

ees/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('about/', include('school.urls', namespace='aboutus')),
    path('circular/', include('circular.urls', namespace='circular')),
    path('events/', include('events.urls', namespace='events')),
    path('achievements/', include('achievements.urls', namespace='achievements')),
    path('studentcouncil/', include('studentcouncil.urls', namespace='studentcouncil')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('missionstatement/', include('missionstatement.urls', namespace='missionstatement')),
    path('forcebehind/', include('forcebehind.urls', namespace='forcebehind')),
    path('members/', include('members.urls', namespace='members')),
    path('infrastructure/', include('infrastructure.urls', namespace='infrastructure')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('admissions/', include('admissions.urls', namespace='admissions')),
    path('ncc/', include('ncc.urls', namespace='ncc')),
    path('academics/', include('academics.urls', namespace='academics')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "EEHS SCHOOL ADMIN"
admin.site.site_title = "EEHS SCHOOL ADMIN"
admin.site.site_index_title = "Welcome To EEHS School Admin Panel"

circular/models.py
from django.db import models
from datetime import date
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    category_year = models.CharField(max_length=30)
    slug = models.SlugField(max_length=250,default="")

    def __str__(self):
        return '{}'.format(self.category_year)

    def get_url(self):
	    return reverse('circular:circular_category', args=[self.slug])	    

    class Meta:
        ordering = ('category_year',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'   

class Circular(models.Model):
    date = models.DateField()
    
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)
    circular_notice = models.CharField(max_length=150,default="")
    slug = models.SlugField(max_length=250,default="")
    circular_details_two = models.TextField(default="") 

    def __str__(self):
        return str(self.date)
        

    class Meta:
        ordering = ('circular_notice',)
        verbose_name = 'Circular'
        verbose_name_plural = 'Circulars'

   

circular/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Circular, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.
# def circular(request):    
#     circular = Circular.objects.all()
#     template = 'circular/circular.html'
#     context = {
#         'circular': circular
#     }
#     return render(request, template, context)

def circular(request, c_slug=None):
	c_page = None
	circular_list = None
	if c_slug != None:
		c_page = get_object_or_404(Category,slug=c_slug)
		circular_list  = Circular.objects.filter(category=c_page)
	else:
		circular_list  = Circular.objects.all().filter()
	'''Pagination code'''
	paginator= Paginator(circular_list , 6)
	try:
		page = int(request.GET.get('page','1'))
	except:
		page = 1
	try:
		circular = paginator.page(page)
	except (EmptyPage,InvalidPage):
		circular = paginator.page(paginator.num_pages)
	return render(request, 'circular/circular.html',{'category':c_page, 'circular':circular})

circular/templates/circular/circular.html
{% extends 'base.html' %}

{% block body %}
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Circular</h2>
                <div class="page_link">
                    <a href="/">Home</a>
                    <a href="{% url 'circular:circular' %}">Circular</a>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
        {% include 'navbar.html' %}
    </div>
    {% if category %}
<div>
    <h1 class="text-center my_title">Circular {{category.category_year}}</h1>
    <hr>
</div>
{% else %}
<br>
<div>
    <h1 class="text-center my_title">Circulars</h1>
   <hr>
</div>
{% endif %}
    <div class="container">
    <div class="row mx-auto">
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Circular Date</th>
                <th scope="col">Circular Notice</th>
                <th scope="col">Circular Details</th>
              </tr>
            </thead>
        {% for circular in circular.object_list %}
        
            <tbody>
              <tr>
                <th scope="row">{{circular.date}}</th>
                <td>{{circular.circular_notice|safe|escape}}</td>
                <td>{{circular.circular_details_two|safe|escape}}</td>
              </tr>
       
  
            </tbody>
            {% endfor %}
          </table>
       
    </div>
    <div class="mx-auto">
        {% if circular.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in circular.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if circular.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

<!-- <section class="about_area p_120">
    <div class="container">
        <div class="row">
            {% for x in circular %}
            <a href="{{x.category}}">{{x.category}}</a>
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                           {{x.circular_notice}}-{{x.date}}
                        </button>
                        </h2>
                    </div>
                
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                        {{x.circular_details_two}}
                        </div>
                    </div>
                </div>
             
            </div>
            {% endfor %}
        </div>
    </div>
</section>    -->

</div>

{% endblock body %}   